version: '3.9'

services:
  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:v2.39.1
    ports:
    - 19090:9090
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    - ./prometheus/rules.yml:/etc/prometheus/rules.yml

  alertmanager:
    container_name: alertmanager
    hostname: alertmanager
    image: prom/alertmanager:v0.24.0
    ports:
    - 19093:9093
    volumes:
    - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:9.2.1
    ports:
      - 13000:3000
    volumes:
    - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    - ./grafana/dashboards:/var/lib/grafana/dashboards      
    environment:
    - GF_AUTH_DISABLE_LOGIN_FORM=${GF_AUTH_DISABLE_LOGIN_FORM}
    - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}
    - GF_AUTH_ANONYMOUS_ORG_NAME=${GF_AUTH_ANONYMOUS_ORG_NAME}
    - GF_AUTH_ANONYMOUS_ORG_ROLE=${GF_AUTH_ANONYMOUS_ORG_ROLE}
